# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_user_window.ui'
#
# Created: Sat Jan 25 23:24:27 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_AddUserWindow(object):
    def setupUi(self, AddUserWindow):
        AddUserWindow.setObjectName("AddUserWindow")
        AddUserWindow.setWindowModality(QtCore.Qt.WindowModal)
        AddUserWindow.resize(380, 360)
        self.verticalLayout = QtGui.QVBoxLayout(AddUserWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainLayout = QtGui.QHBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.left = QtGui.QVBoxLayout()
        self.left.setObjectName("left")
        self.label = QtGui.QLabel(AddUserWindow)
        self.label.setObjectName("label")
        self.left.addWidget(self.label)
        self.knownUsersList = QtGui.QListWidget(AddUserWindow)
        self.knownUsersList.setAlternatingRowColors(True)
        self.knownUsersList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.knownUsersList.setObjectName("knownUsersList")
        self.left.addWidget(self.knownUsersList)
        self.mainLayout.addLayout(self.left)
        self.addButtonsLayout = QtGui.QVBoxLayout()
        self.addButtonsLayout.setObjectName("addButtonsLayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.addButtonsLayout.addItem(spacerItem)
        self.addButton = QtGui.QPushButton(AddUserWindow)
        self.addButton.setObjectName("addButton")
        self.addButtonsLayout.addWidget(self.addButton)
        self.addAllButton = QtGui.QPushButton(AddUserWindow)
        self.addAllButton.setObjectName("addAllButton")
        self.addButtonsLayout.addWidget(self.addAllButton)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.addButtonsLayout.addItem(spacerItem1)
        self.removeButton = QtGui.QPushButton(AddUserWindow)
        self.removeButton.setObjectName("removeButton")
        self.addButtonsLayout.addWidget(self.removeButton)
        self.removeAllButton = QtGui.QPushButton(AddUserWindow)
        self.removeAllButton.setObjectName("removeAllButton")
        self.addButtonsLayout.addWidget(self.removeAllButton)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.addButtonsLayout.addItem(spacerItem2)
        self.mainLayout.addLayout(self.addButtonsLayout)
        self.right = QtGui.QVBoxLayout()
        self.right.setObjectName("right")
        self.label_2 = QtGui.QLabel(AddUserWindow)
        self.label_2.setObjectName("label_2")
        self.right.addWidget(self.label_2)
        self.recipientsList = QtGui.QListWidget(AddUserWindow)
        self.recipientsList.setAlternatingRowColors(True)
        self.recipientsList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.recipientsList.setObjectName("recipientsList")
        self.right.addWidget(self.recipientsList)
        self.mainLayout.addLayout(self.right)
        self.verticalLayout.addLayout(self.mainLayout)
        self.unknownForm = QtGui.QHBoxLayout()
        self.unknownForm.setObjectName("unknownForm")
        self.addUserLabel = QtGui.QLabel(AddUserWindow)
        self.addUserLabel.setObjectName("addUserLabel")
        self.unknownForm.addWidget(self.addUserLabel)
        self.unknownUserEdit = QtGui.QLineEdit(AddUserWindow)
        self.unknownUserEdit.setObjectName("unknownUserEdit")
        self.unknownForm.addWidget(self.unknownUserEdit)
        self.addUnknownButton = QtGui.QPushButton(AddUserWindow)
        self.addUnknownButton.setObjectName("addUnknownButton")
        self.unknownForm.addWidget(self.addUnknownButton)
        self.verticalLayout.addLayout(self.unknownForm)
        self.confirmButtons = QtGui.QHBoxLayout()
        self.confirmButtons.setObjectName("confirmButtons")
        self.doneButton = QtGui.QPushButton(AddUserWindow)
        self.doneButton.setObjectName("doneButton")
        self.confirmButtons.addWidget(self.doneButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.confirmButtons.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.confirmButtons)

        self.retranslateUi(AddUserWindow)
        QtCore.QMetaObject.connectSlotsByName(AddUserWindow)

    def retranslateUi(self, AddUserWindow):
        AddUserWindow.setWindowTitle(QtGui.QApplication.translate("AddUserWindow", "Select recipients", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AddUserWindow", "Known users:", None, QtGui.QApplication.UnicodeUTF8))
        self.knownUsersList.setSortingEnabled(True)
        self.addButton.setToolTip(QtGui.QApplication.translate("AddUserWindow", "Add selected users", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("AddUserWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.addAllButton.setToolTip(QtGui.QApplication.translate("AddUserWindow", "Add all users", None, QtGui.QApplication.UnicodeUTF8))
        self.addAllButton.setText(QtGui.QApplication.translate("AddUserWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.removeButton.setToolTip(QtGui.QApplication.translate("AddUserWindow", "Remove selected recipients", None, QtGui.QApplication.UnicodeUTF8))
        self.removeButton.setText(QtGui.QApplication.translate("AddUserWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.removeAllButton.setToolTip(QtGui.QApplication.translate("AddUserWindow", "Remove all recipients", None, QtGui.QApplication.UnicodeUTF8))
        self.removeAllButton.setText(QtGui.QApplication.translate("AddUserWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("AddUserWindow", "Selected recipients:", None, QtGui.QApplication.UnicodeUTF8))
        self.recipientsList.setSortingEnabled(True)
        self.addUserLabel.setText(QtGui.QApplication.translate("AddUserWindow", "Add new user:", None, QtGui.QApplication.UnicodeUTF8))
        self.addUnknownButton.setText(QtGui.QApplication.translate("AddUserWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.doneButton.setText(QtGui.QApplication.translate("AddUserWindow", "Done", None, QtGui.QApplication.UnicodeUTF8))

